version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:18.0.2

    steps:
      - checkout
      - run:
          command: chmod +x mvnw
      - run:
          name: Build and Tests
          command: ./mvnw clean package
      - run:
          name: Analyze on SonarCloud
          command: ./mvnw verify sonar:sonar -Dsonar.projectKey=viniciuslj_vote-api

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud